# Generated by Django 3.2.15 on 2022-11-23 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionUsuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender_id', models.IntegerField()),
                ('text', models.CharField(max_length=100)),
                ('created_at', models.DateField()),
            ],
        ),
    ]
