# Generated by Django 3.2.15 on 2022-11-27 00:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestionUsuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IdentifierNamePokemon',
            fields=[
                ('identifier', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='TypePokemon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(blank=True, max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Pokemon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_species', models.IntegerField()),
                ('height', models.IntegerField()),
                ('weight', models.IntegerField()),
                ('hp', models.IntegerField()),
                ('attack', models.IntegerField()),
                ('sp_attack', models.IntegerField()),
                ('defense', models.IntegerField()),
                ('sp_defense', models.IntegerField()),
                ('speed', models.IntegerField()),
                ('type1_id', models.IntegerField()),
                ('type2_id', models.IntegerField()),
                ('identifier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestionUsuarios.identifiernamepokemon')),
            ],
        ),
        migrations.CreateModel(
            name='Box',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('lvl_pkmn', models.IntegerField()),
                ('nickname_pkmn', models.CharField(max_length=50)),
                ('pkmn_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestionUsuarios.pokemon')),
            ],
        ),
    ]
