# Generated by Django 3.2.15 on 2022-11-27 03:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestionUsuarios', '0002_box_identifiernamepokemon_pokemon_typepokemon'),
        ('gestionUsuarios', '0002_feedback'),
    ]

    operations = [
    ]
