# Generated by Django 3.2.15 on 2022-11-27 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionUsuarios', '0003_merge_20221127_0056'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pokemon',
            name='identifier',
        ),
        migrations.DeleteModel(
            name='TypePokemon',
        ),
        migrations.AlterField(
            model_name='box',
            name='pkmn_id',
            field=models.IntegerField(),
        ),
        migrations.DeleteModel(
            name='IdentifierNamePokemon',
        ),
        migrations.DeleteModel(
            name='Pokemon',
        ),
    ]
