# Generated by Django 3.2.15 on 2022-11-27 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DescriptionPokemon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('AlphaSapphire', models.CharField(blank=True, max_length=200, null=True)),
                ('Black', models.CharField(blank=True, max_length=200, null=True)),
                ('Black2', models.CharField(blank=True, max_length=200, null=True)),
                ('Blue', models.CharField(blank=True, max_length=200, null=True)),
                ('Crystal', models.CharField(blank=True, max_length=200, null=True)),
                ('Diamond', models.CharField(blank=True, max_length=200, null=True)),
                ('Emerald', models.CharField(blank=True, max_length=200, null=True)),
                ('Firered', models.CharField(blank=True, max_length=200, null=True)),
                ('Gold', models.CharField(blank=True, max_length=200, null=True)),
                ('Heartgold', models.CharField(blank=True, max_length=200, null=True)),
                ('Leafgreen', models.CharField(blank=True, max_length=200, null=True)),
                ('LetsGoEevee', models.CharField(blank=True, max_length=200, null=True)),
                ('LetsGoPikachu', models.CharField(blank=True, max_length=200, null=True)),
                ('Moon', models.CharField(blank=True, max_length=200, null=True)),
                ('OmegaRuby', models.CharField(blank=True, max_length=200, null=True)),
                ('Pearl', models.CharField(blank=True, max_length=200, null=True)),
                ('Platinum', models.CharField(blank=True, max_length=200, null=True)),
                ('Red', models.CharField(blank=True, max_length=200, null=True)),
                ('Ruby', models.CharField(blank=True, max_length=200, null=True)),
                ('Sapphire', models.CharField(blank=True, max_length=200, null=True)),
                ('Shield', models.CharField(blank=True, max_length=200, null=True)),
                ('Silver', models.CharField(blank=True, max_length=200, null=True)),
                ('Soulsilver', models.CharField(blank=True, max_length=200, null=True)),
                ('Sun', models.CharField(blank=True, max_length=200, null=True)),
                ('Sword', models.CharField(blank=True, max_length=200, null=True)),
                ('UltraMoon', models.CharField(blank=True, max_length=200, null=True)),
                ('UltraSun', models.CharField(blank=True, max_length=200, null=True)),
                ('White', models.CharField(blank=True, max_length=200, null=True)),
                ('White2', models.CharField(blank=True, max_length=200, null=True)),
                ('X', models.CharField(blank=True, max_length=200, null=True)),
                ('Y', models.CharField(blank=True, max_length=200, null=True)),
                ('Yellow', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='IdentifierNamePokemon',
            fields=[
                ('identifier', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Pokemon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.CharField(blank=True, max_length=200, null=True)),
                ('id_species', models.IntegerField()),
                ('height', models.IntegerField()),
                ('weight', models.IntegerField()),
                ('hp', models.IntegerField()),
                ('attack', models.IntegerField()),
                ('sp_attack', models.IntegerField()),
                ('defense', models.IntegerField()),
                ('sp_defense', models.IntegerField()),
                ('speed', models.IntegerField()),
                ('type1_id', models.IntegerField()),
                ('type2_id', models.IntegerField()),
            ],
        ),
    ]
