# Generated by Django 3.2.15 on 2022-11-28 00:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WikiDex', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pokemon',
            old_name='id_species',
            new_name='species_id',
        ),
    ]
