# Generated by Django 3.2.15 on 2022-11-28 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WikiDex', '0002_rename_id_species_pokemon_species_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pokemon',
            name='type1_id',
        ),
        migrations.RemoveField(
            model_name='pokemon',
            name='type2_id',
        ),
        migrations.AddField(
            model_name='pokemon',
            name='type1',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='pokemon',
            name='type2',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
