# Generated by Django 3.2.15 on 2022-11-28 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WikiDex', '0003_auto_20221127_2132'),
    ]

    operations = [
        migrations.CreateModel(
            name='FormsPokemon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('form_name', models.CharField(blank=True, max_length=100, null=True)),
                ('pokemon_name', models.CharField(blank=True, max_length=100, null=True)),
                ('pokemon_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='SpeciesPokemon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('evolution_chain_id', models.IntegerField()),
                ('order', models.IntegerField()),
            ],
        ),
    ]
