# Generated by Django 3.2.15 on 2022-11-28 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WikiDex', '0004_formspokemon_speciespokemon'),
    ]

    operations = [
        migrations.AddField(
            model_name='formspokemon',
            name='identifier',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
