# Generated by Django 3.2.15 on 2022-11-28 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WikiDex', '0005_formspokemon_identifier'),
    ]

    operations = [
        migrations.AddField(
            model_name='speciespokemon',
            name='identifier',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
